# Generated by Django 3.1.5 on 2021-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank='false', db_column='name', max_length=100)),
                ('email', models.CharField(blank='false', db_column='email', max_length=50)),
            ],
        ),
    ]
